/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QWidget *waveWidget;
    QLabel *ecg1Label;
    QLabel *ecg1WaveLabel;
    QLabel *ecg2WaveLabel;
    QLabel *ecg2Label;
    QLabel *spo2WaveLabel;
    QLabel *spo2Label;
    QWidget *paraDataWidget;
    QGroupBox *tempInfoGroupBox;
    QLabel *tempUnitLabel;
    QLabel *temp1Label;
    QLabel *temp2Label;
    QLabel *temp1LeadLabel;
    QLabel *temp2LeadLabel;
    QLabel *temp1ValLabel;
    QLabel *temp2ValLabel;
    QGroupBox *respInfoGroupBox;
    QLabel *respUnitLabel;
    QLabel *respRateLabel;
    QGroupBox *spo2InfoGroupBox;
    QLabel *spo2InfoLabel;
    QLabel *pulseRateLabel;
    QLabel *spo2DataLabel;
    QLabel *spo2UnitLabel;
    QLabel *spo2PRLabel;
    QLabel *spo2PRUnitLabel;
    QLabel *spo2FingerLeadLabel;
    QLabel *spo2PrbLeadLabel;
    QGroupBox *nibpInfoGroupBox;
    QLabel *nibpUnitLabel;
    QLabel *cufPressureLabel;
    QLabel *mapPressureLabel;
    QLabel *sysPressureLabel;
    QLabel *diaPressureLabel;
    QLabel *nibpModeLabel;
    QLabel *nibpPRLabel;
    QLabel *nibpPRUnitLabel;
    QLabel *slashLabel;
    QGroupBox *ecgInfoGroupBox;
    QLabel *heartRateUnitLabel;
    QLabel *leadRALabel;
    QLabel *leadLALabel;
    QLabel *leadLLLabel;
    QLabel *heartRateLabel;
    QLabel *leadVLabel;
    QLabel *respWaveLabel;
    QLabel *respLabel;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1628, 962);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        waveWidget = new QWidget(centralWidget);
        waveWidget->setObjectName(QString::fromUtf8("waveWidget"));
        waveWidget->setGeometry(QRect(9, 9, 1111, 681));
        ecg1Label = new QLabel(waveWidget);
        ecg1Label->setObjectName(QString::fromUtf8("ecg1Label"));
        ecg1Label->setGeometry(QRect(30, 10, 81, 21));
        QPalette palette;
        QBrush brush(QColor(231, 231, 231, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush2(QColor(231, 231, 231, 128));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        ecg1Label->setPalette(palette);
        ecg1WaveLabel = new QLabel(waveWidget);
        ecg1WaveLabel->setObjectName(QString::fromUtf8("ecg1WaveLabel"));
        ecg1WaveLabel->setGeometry(QRect(30, 40, 1081, 171));
        QPalette palette1;
        QBrush brush3(QColor(0, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        ecg1WaveLabel->setPalette(palette1);
        ecg2WaveLabel = new QLabel(waveWidget);
        ecg2WaveLabel->setObjectName(QString::fromUtf8("ecg2WaveLabel"));
        ecg2WaveLabel->setGeometry(QRect(30, 250, 1081, 191));
        ecg2Label = new QLabel(waveWidget);
        ecg2Label->setObjectName(QString::fromUtf8("ecg2Label"));
        ecg2Label->setGeometry(QRect(30, 215, 81, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        ecg2Label->setPalette(palette2);
        spo2WaveLabel = new QLabel(waveWidget);
        spo2WaveLabel->setObjectName(QString::fromUtf8("spo2WaveLabel"));
        spo2WaveLabel->setGeometry(QRect(30, 480, 1081, 201));
        spo2WaveLabel->setStyleSheet(QString::fromUtf8(""));
        spo2Label = new QLabel(waveWidget);
        spo2Label->setObjectName(QString::fromUtf8("spo2Label"));
        spo2Label->setGeometry(QRect(30, 450, 81, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2Label->setPalette(palette3);
        paraDataWidget = new QWidget(centralWidget);
        paraDataWidget->setObjectName(QString::fromUtf8("paraDataWidget"));
        paraDataWidget->setGeometry(QRect(1130, 10, 201, 681));
        tempInfoGroupBox = new QGroupBox(centralWidget);
        tempInfoGroupBox->setObjectName(QString::fromUtf8("tempInfoGroupBox"));
        tempInfoGroupBox->setGeometry(QRect(1380, 710, 201, 201));
        tempInfoGroupBox->setStyleSheet(QString::fromUtf8("        QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }"));
        tempUnitLabel = new QLabel(tempInfoGroupBox);
        tempUnitLabel->setObjectName(QString::fromUtf8("tempUnitLabel"));
        tempUnitLabel->setGeometry(QRect(10, 10, 181, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        tempUnitLabel->setPalette(palette4);
        QFont font;
        font.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font.setPointSize(12);
        tempUnitLabel->setFont(font);
        temp1Label = new QLabel(tempInfoGroupBox);
        temp1Label->setObjectName(QString::fromUtf8("temp1Label"));
        temp1Label->setGeometry(QRect(0, 40, 51, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp1Label->setPalette(palette5);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\260\345\256\213\344\275\223"));
        font1.setPointSize(12);
        temp1Label->setFont(font1);
        temp2Label = new QLabel(tempInfoGroupBox);
        temp2Label->setObjectName(QString::fromUtf8("temp2Label"));
        temp2Label->setGeometry(QRect(0, 70, 51, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp2Label->setPalette(palette6);
        temp2Label->setFont(font);
        temp1LeadLabel = new QLabel(tempInfoGroupBox);
        temp1LeadLabel->setObjectName(QString::fromUtf8("temp1LeadLabel"));
        temp1LeadLabel->setGeometry(QRect(0, 100, 101, 41));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp1LeadLabel->setPalette(palette7);
        temp1LeadLabel->setFont(font);
        temp2LeadLabel = new QLabel(tempInfoGroupBox);
        temp2LeadLabel->setObjectName(QString::fromUtf8("temp2LeadLabel"));
        temp2LeadLabel->setGeometry(QRect(0, 150, 101, 41));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp2LeadLabel->setPalette(palette8);
        temp2LeadLabel->setFont(font);
        temp1ValLabel = new QLabel(tempInfoGroupBox);
        temp1ValLabel->setObjectName(QString::fromUtf8("temp1ValLabel"));
        temp1ValLabel->setGeometry(QRect(60, 40, 71, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp1ValLabel->setPalette(palette9);
        temp1ValLabel->setFont(font);
        temp2ValLabel = new QLabel(tempInfoGroupBox);
        temp2ValLabel->setObjectName(QString::fromUtf8("temp2ValLabel"));
        temp2ValLabel->setGeometry(QRect(60, 60, 71, 41));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        temp2ValLabel->setPalette(palette10);
        temp2ValLabel->setFont(font);
        respInfoGroupBox = new QGroupBox(centralWidget);
        respInfoGroupBox->setObjectName(QString::fromUtf8("respInfoGroupBox"));
        respInfoGroupBox->setGeometry(QRect(1200, 710, 181, 201));
        respInfoGroupBox->setStyleSheet(QString::fromUtf8("        QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }"));
        respUnitLabel = new QLabel(respInfoGroupBox);
        respUnitLabel->setObjectName(QString::fromUtf8("respUnitLabel"));
        respUnitLabel->setGeometry(QRect(10, 10, 161, 41));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        respUnitLabel->setPalette(palette11);
        respUnitLabel->setFont(font);
        respRateLabel = new QLabel(respInfoGroupBox);
        respRateLabel->setObjectName(QString::fromUtf8("respRateLabel"));
        respRateLabel->setGeometry(QRect(60, 80, 81, 71));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        respRateLabel->setPalette(palette12);
        respRateLabel->setFont(font);
        spo2InfoGroupBox = new QGroupBox(centralWidget);
        spo2InfoGroupBox->setObjectName(QString::fromUtf8("spo2InfoGroupBox"));
        spo2InfoGroupBox->setGeometry(QRect(1200, 480, 381, 221));
        spo2InfoGroupBox->setStyleSheet(QString::fromUtf8("        QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }"));
        spo2InfoLabel = new QLabel(spo2InfoGroupBox);
        spo2InfoLabel->setObjectName(QString::fromUtf8("spo2InfoLabel"));
        spo2InfoLabel->setGeometry(QRect(50, 10, 81, 51));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        QBrush brush4(QColor(255, 255, 255, 127));
        brush4.setStyle(Qt::SolidPattern);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        spo2InfoLabel->setPalette(palette13);
        spo2InfoLabel->setFont(font1);
        pulseRateLabel = new QLabel(spo2InfoGroupBox);
        pulseRateLabel->setObjectName(QString::fromUtf8("pulseRateLabel"));
        pulseRateLabel->setGeometry(QRect(210, 10, 81, 51));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        pulseRateLabel->setPalette(palette14);
        pulseRateLabel->setFont(font1);
        spo2DataLabel = new QLabel(spo2InfoGroupBox);
        spo2DataLabel->setObjectName(QString::fromUtf8("spo2DataLabel"));
        spo2DataLabel->setGeometry(QRect(50, 100, 41, 41));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2DataLabel->setPalette(palette15);
        spo2DataLabel->setFont(font1);
        spo2UnitLabel = new QLabel(spo2InfoGroupBox);
        spo2UnitLabel->setObjectName(QString::fromUtf8("spo2UnitLabel"));
        spo2UnitLabel->setGeometry(QRect(90, 100, 41, 41));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2UnitLabel->setPalette(palette16);
        spo2UnitLabel->setFont(font1);
        spo2PRLabel = new QLabel(spo2InfoGroupBox);
        spo2PRLabel->setObjectName(QString::fromUtf8("spo2PRLabel"));
        spo2PRLabel->setGeometry(QRect(220, 110, 51, 31));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2PRLabel->setPalette(palette17);
        spo2PRLabel->setFont(font1);
        spo2PRUnitLabel = new QLabel(spo2InfoGroupBox);
        spo2PRUnitLabel->setObjectName(QString::fromUtf8("spo2PRUnitLabel"));
        spo2PRUnitLabel->setGeometry(QRect(260, 110, 61, 31));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2PRUnitLabel->setPalette(palette18);
        spo2PRUnitLabel->setFont(font1);
        spo2FingerLeadLabel = new QLabel(spo2InfoGroupBox);
        spo2FingerLeadLabel->setObjectName(QString::fromUtf8("spo2FingerLeadLabel"));
        spo2FingerLeadLabel->setGeometry(QRect(10, 150, 141, 61));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2FingerLeadLabel->setPalette(palette19);
        spo2FingerLeadLabel->setFont(font1);
        spo2PrbLeadLabel = new QLabel(spo2InfoGroupBox);
        spo2PrbLeadLabel->setObjectName(QString::fromUtf8("spo2PrbLeadLabel"));
        spo2PrbLeadLabel->setGeometry(QRect(230, 150, 141, 61));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        spo2PrbLeadLabel->setPalette(palette20);
        spo2PrbLeadLabel->setFont(font1);
        nibpInfoGroupBox = new QGroupBox(centralWidget);
        nibpInfoGroupBox->setObjectName(QString::fromUtf8("nibpInfoGroupBox"));
        nibpInfoGroupBox->setGeometry(QRect(1200, 260, 381, 211));
        nibpInfoGroupBox->setStyleSheet(QString::fromUtf8("        QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }"));
        nibpUnitLabel = new QLabel(nibpInfoGroupBox);
        nibpUnitLabel->setObjectName(QString::fromUtf8("nibpUnitLabel"));
        nibpUnitLabel->setGeometry(QRect(10, 10, 361, 41));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        nibpUnitLabel->setPalette(palette21);
        nibpUnitLabel->setFont(font1);
        cufPressureLabel = new QLabel(nibpInfoGroupBox);
        cufPressureLabel->setObjectName(QString::fromUtf8("cufPressureLabel"));
        cufPressureLabel->setGeometry(QRect(30, 50, 81, 41));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush);
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        cufPressureLabel->setPalette(palette22);
        cufPressureLabel->setFont(font1);
        mapPressureLabel = new QLabel(nibpInfoGroupBox);
        mapPressureLabel->setObjectName(QString::fromUtf8("mapPressureLabel"));
        mapPressureLabel->setGeometry(QRect(230, 40, 71, 41));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush);
        palette23.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        mapPressureLabel->setPalette(palette23);
        mapPressureLabel->setFont(font1);
        sysPressureLabel = new QLabel(nibpInfoGroupBox);
        sysPressureLabel->setObjectName(QString::fromUtf8("sysPressureLabel"));
        sysPressureLabel->setGeometry(QRect(90, 80, 71, 51));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette24.setBrush(QPalette::Active, QPalette::Text, brush);
        palette24.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        sysPressureLabel->setPalette(palette24);
        sysPressureLabel->setFont(font1);
        diaPressureLabel = new QLabel(nibpInfoGroupBox);
        diaPressureLabel->setObjectName(QString::fromUtf8("diaPressureLabel"));
        diaPressureLabel->setGeometry(QRect(210, 80, 81, 51));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Text, brush);
        palette25.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette25.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        diaPressureLabel->setPalette(palette25);
        diaPressureLabel->setFont(font1);
        nibpModeLabel = new QLabel(nibpInfoGroupBox);
        nibpModeLabel->setObjectName(QString::fromUtf8("nibpModeLabel"));
        nibpModeLabel->setGeometry(QRect(10, 140, 101, 51));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush);
        palette26.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette26.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        nibpModeLabel->setPalette(palette26);
        nibpModeLabel->setFont(font1);
        nibpPRLabel = new QLabel(nibpInfoGroupBox);
        nibpPRLabel->setObjectName(QString::fromUtf8("nibpPRLabel"));
        nibpPRLabel->setGeometry(QRect(220, 150, 61, 41));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette27.setBrush(QPalette::Active, QPalette::Text, brush);
        palette27.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette27.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        nibpPRLabel->setPalette(palette27);
        nibpPRLabel->setFont(font1);
        nibpPRUnitLabel = new QLabel(nibpInfoGroupBox);
        nibpPRUnitLabel->setObjectName(QString::fromUtf8("nibpPRUnitLabel"));
        nibpPRUnitLabel->setGeometry(QRect(270, 140, 71, 51));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Text, brush);
        palette28.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        nibpPRUnitLabel->setPalette(palette28);
        nibpPRUnitLabel->setFont(font1);
        slashLabel = new QLabel(nibpInfoGroupBox);
        slashLabel->setObjectName(QString::fromUtf8("slashLabel"));
        slashLabel->setGeometry(QRect(160, 80, 51, 51));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush);
        palette29.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        slashLabel->setPalette(palette29);
        slashLabel->setFont(font1);
        ecgInfoGroupBox = new QGroupBox(centralWidget);
        ecgInfoGroupBox->setObjectName(QString::fromUtf8("ecgInfoGroupBox"));
        ecgInfoGroupBox->setGeometry(QRect(1200, 40, 381, 211));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        ecgInfoGroupBox->setPalette(palette30);
        ecgInfoGroupBox->setStyleSheet(QString::fromUtf8("        QGroupBox {\n"
"            border-color: rgb(156, 156, 156);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }"));
        ecgInfoGroupBox->setFlat(false);
        heartRateUnitLabel = new QLabel(ecgInfoGroupBox);
        heartRateUnitLabel->setObjectName(QString::fromUtf8("heartRateUnitLabel"));
        heartRateUnitLabel->setGeometry(QRect(10, 10, 361, 41));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        heartRateUnitLabel->setPalette(palette31);
        heartRateUnitLabel->setFont(font1);
        leadRALabel = new QLabel(ecgInfoGroupBox);
        leadRALabel->setObjectName(QString::fromUtf8("leadRALabel"));
        leadRALabel->setGeometry(QRect(10, 50, 31, 31));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Text, brush);
        palette32.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette32.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        leadRALabel->setPalette(palette32);
        leadRALabel->setFont(font1);
        leadLALabel = new QLabel(ecgInfoGroupBox);
        leadLALabel->setObjectName(QString::fromUtf8("leadLALabel"));
        leadLALabel->setGeometry(QRect(10, 90, 31, 31));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Text, brush);
        palette33.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette33.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette33.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette33.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        leadLALabel->setPalette(palette33);
        leadLALabel->setFont(font1);
        leadLLLabel = new QLabel(ecgInfoGroupBox);
        leadLLLabel->setObjectName(QString::fromUtf8("leadLLLabel"));
        leadLLLabel->setGeometry(QRect(10, 140, 41, 41));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Text, brush);
        palette34.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette34.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette34.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette34.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        leadLLLabel->setPalette(palette34);
        leadLLLabel->setFont(font1);
        heartRateLabel = new QLabel(ecgInfoGroupBox);
        heartRateLabel->setObjectName(QString::fromUtf8("heartRateLabel"));
        heartRateLabel->setGeometry(QRect(240, 50, 61, 51));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Text, brush);
        palette35.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette35.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        heartRateLabel->setPalette(palette35);
        heartRateLabel->setFont(font1);
        leadVLabel = new QLabel(ecgInfoGroupBox);
        leadVLabel->setObjectName(QString::fromUtf8("leadVLabel"));
        leadVLabel->setGeometry(QRect(260, 120, 41, 41));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Text, brush);
        palette36.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette36.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        leadVLabel->setPalette(palette36);
        leadVLabel->setFont(font1);
        respWaveLabel = new QLabel(centralWidget);
        respWaveLabel->setObjectName(QString::fromUtf8("respWaveLabel"));
        respWaveLabel->setGeometry(QRect(40, 720, 1081, 191));
        respLabel = new QLabel(centralWidget);
        respLabel->setObjectName(QString::fromUtf8("respLabel"));
        respLabel->setGeometry(QRect(40, 690, 61, 21));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Text, brush);
        palette37.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette37.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        respLabel->setPalette(palette37);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1628, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush5(QColor(93, 93, 93, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette38.setBrush(QPalette::Active, QPalette::Button, brush5);
        QBrush brush6(QColor(70, 70, 70, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette38.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush);
        palette38.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette38.setBrush(QPalette::Active, QPalette::PlaceholderText, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette38.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette38.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush2);
        mainToolBar->setPalette(palette38);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        ecg1Label->setText(QApplication::translate("MainWindow", "ECG1", nullptr));
        ecg1WaveLabel->setText(QString());
        ecg2WaveLabel->setText(QString());
        ecg2Label->setText(QApplication::translate("MainWindow", "ECG2", nullptr));
        spo2WaveLabel->setText(QString());
        spo2Label->setText(QApplication::translate("MainWindow", "SPO2", nullptr));
        tempInfoGroupBox->setTitle(QString());
        tempUnitLabel->setText(QApplication::translate("MainWindow", "\344\275\223\346\270\251 \342\204\203", nullptr));
        temp1Label->setText(QApplication::translate("MainWindow", "T1:", nullptr));
        temp2Label->setText(QApplication::translate("MainWindow", "T2:", nullptr));
        temp1LeadLabel->setText(QApplication::translate("MainWindow", "T1\350\204\261\350\220\275", nullptr));
        temp2LeadLabel->setText(QApplication::translate("MainWindow", "T2\350\204\261\350\220\275", nullptr));
        temp1ValLabel->setText(QApplication::translate("MainWindow", "--", nullptr));
        temp2ValLabel->setText(QApplication::translate("MainWindow", "--", nullptr));
        respInfoGroupBox->setTitle(QString());
        respUnitLabel->setText(QApplication::translate("MainWindow", "\345\221\274\345\220\270 bpm", nullptr));
        respRateLabel->setText(QApplication::translate("MainWindow", "---", nullptr));
        spo2InfoGroupBox->setTitle(QString());
        spo2InfoLabel->setText(QApplication::translate("MainWindow", "\350\241\200\346\260\247", nullptr));
        pulseRateLabel->setText(QApplication::translate("MainWindow", "\350\204\211\347\216\207", nullptr));
        spo2DataLabel->setText(QApplication::translate("MainWindow", "--", nullptr));
        spo2UnitLabel->setText(QApplication::translate("MainWindow", "%", nullptr));
        spo2PRLabel->setText(QApplication::translate("MainWindow", "--", nullptr));
        spo2PRUnitLabel->setText(QApplication::translate("MainWindow", "bpm", nullptr));
        spo2FingerLeadLabel->setText(QApplication::translate("MainWindow", "\346\211\213\346\214\207\350\204\261\350\220\275", nullptr));
        spo2PrbLeadLabel->setText(QApplication::translate("MainWindow", "\346\216\242\345\244\264\350\204\261\350\220\275", nullptr));
        nibpInfoGroupBox->setTitle(QString());
        nibpUnitLabel->setText(QApplication::translate("MainWindow", "\346\227\240\345\210\233\350\241\200\345\216\213      mmHg", nullptr));
        cufPressureLabel->setText(QApplication::translate("MainWindow", "----", nullptr));
        mapPressureLabel->setText(QApplication::translate("MainWindow", "----", nullptr));
        sysPressureLabel->setText(QApplication::translate("MainWindow", "---", nullptr));
        diaPressureLabel->setText(QApplication::translate("MainWindow", "---", nullptr));
        nibpModeLabel->setText(QApplication::translate("MainWindow", "\346\211\213\345\212\250", nullptr));
        nibpPRLabel->setText(QApplication::translate("MainWindow", "---", nullptr));
        nibpPRUnitLabel->setText(QApplication::translate("MainWindow", "bpm", nullptr));
        slashLabel->setText(QApplication::translate("MainWindow", "/", nullptr));
        ecgInfoGroupBox->setTitle(QString());
        heartRateUnitLabel->setText(QApplication::translate("MainWindow", "\345\277\203\347\216\207           bpm", nullptr));
        leadRALabel->setText(QApplication::translate("MainWindow", "RA", nullptr));
        leadLALabel->setText(QApplication::translate("MainWindow", "LA", nullptr));
        leadLLLabel->setText(QApplication::translate("MainWindow", "LL", nullptr));
        heartRateLabel->setText(QApplication::translate("MainWindow", "----", nullptr));
        leadVLabel->setText(QApplication::translate("MainWindow", "V", nullptr));
        respWaveLabel->setText(QString());
        respLabel->setText(QApplication::translate("MainWindow", "Resp", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
